version: "2.18.1"
services:
  myappweb:
    image: ghcr.io/kanagalekarv2511/myappweb:latest
    ports:
      - '80:80'

  mydb:
    image: ghcr.io/kanagalekarv2511/mydb:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
#
